### ISSUE TITLE
proposal: add semvar

### ISSUE THREAD

**Issue by alanchchen** [vektra/mockery#121]
I suggest adding semvar to both codegen and the generated code.

E.g.,
```
$ mockery -version
1.0.0
```
```
// Code generated by mockery v1.0.0
// DO NOT EDIT!
```

**Comment by andymc904** [comment]
@evanphx instead of just adding an additional [cli arg](https://github.com/vektra/mockery/blob/master/cmd/mockery/mockery.go#L106-L127), can we migrate this package to use [urfave/cli](https://github.com/urfave/cli)? It has support for the version as requested by this issue plus we'd get a `-help` command for free

**Comment by kingofsouth** [comment]
@alanchchen A change to allow for this was merged in yesterday try merging in master to see if this issue can be closed.
