### ISSUE TITLE
absolute import paths in generated mocks with dependencies in the mocked package

### ISSUE THREAD

**Issue by bsdlp** [vektra/mockery#157]
if I run:

```
mockery -dir "${GOROOT}/src/crypto" -name Signer
```

I would expect the import path in the generated file to be:

```go
import crypto "crypto"
```

However, `mockery` generates:

```go
import crypto "/usr/local/Cellar/go/1.8.1/libexec/src/crypto/"
```

This causes an import error:

```
pkg/mocks/Signer.go:4:15: could not import /usr/local/Cellar/go/1.8.1/libexec/src/crypto/ (import "/usr/local/Cellar/go/1.8.1/libexec/src/crypto/": cannot import absolute path)
```

**Comment by bsdlp** [comment]
looks like this also happens when generating an interface from a vendored package (i have vendor symlinked to __vendor):

```
mockery -dir vendor/github.com/SermoDigital/jose/crypto -name SigningMethod -output ./pkg/mocks
```

Generates diff

```diff
-import crypto "github.com/SermoDigital/jose/crypto"
+import crypto "path/to/repo/__vendor/github.com/SermoDigital/jose/crypto"
```

**Comment by kingofsouth** [comment]
Probably an issue with this guy. https://github.com/vektra/mockery/pull/147

**Comment by bsdlp** [comment]
hmmm, I checked out e786b3035778d53eee64a268b022db3c064d248f and the generated mock still had an absolute import path.

**Comment by kingofsouth** [comment]
Hmm I'll take a look today and see if I can repro it.

**Comment by kingofsouth** [comment]
@bsdlp took a look was didn't repro on my MacBook. Need to investigate more.

**Comment by rolyv** [comment]
FYI, I think it has to do with whether your GOPATH is set or not.

**Comment by danielbprice** [comment]
I am hoping this might help others work around this problem.  This happened to me in a git workspace which is behind a symlink.

On a server I use, `/home/dp/workspace` is a symlink to `/ex0/home/dp/workspace` (this happened because someone was sloppy about disk space in `/home`).

So if I use the workspace as `/home/dp/workspace` (and `GOPATH=/home/dp/workspace/golang`) then I get the absolute path in my generated mock.  If I instead chdir to `/ex0/home/dp/workspace` and set `GOPATH=/ex0/home/dp/workspace` then everything works fine.  So in my Makefile, the workaround to bulletproof things looks like:

```
$(GO_MOCK_CLIENT): $(GOSRCBG)/common/client/client.go | $(MOCKERY) deps-ensured
        cd $(realpath $(@D)/..) && GOPATH=$(realpath $(GOPATH)) $(MOCKERY) -name Client
```

This forces GOPATH and CWD to both be the realpath, and mockery seems happy.  Hopefully this helps someone else.  My guess is that the bug is in some path manipulation inside of mockery having to do with trimming the GOPATH as a prefix.

**Comment by LandonTClipp** [comment]
Closing historic ticket. Please open a new one if you still have issues.
