### ISSUE TITLE
Add option to generate exported mock type for internal interfaces

### ISSUE THREAD

**Issue by pkosiec** [vektra/mockery#191]
#Hi,
Great tool, I really like it! Is there a possibility to add a new option like `-exported=true`, which will make internal interfaces exported?
Please consider an example:

```
//go:generate mockery -name=foo -output=automock -outpkg=automock -case=underscore -exported=true
type foo interface {
	Bar(name string) (string, bool, error)
}
```

It could generate a mock type in `automock` package with a name `Foo`, which is easy to use in test files.

**Alternative:**
It could generate a constructor for this type, which can be used from outside of the `automock` package.

**Comment by LandonTClipp** [comment]
I really like this idea. I'll tag this for consideration.

**Comment by matcornic** [comment]
This option would help me. I have a problem when the mocks on private interface are generated in a different folder than the origin package. It tries to import to origin interface but comilation of the generated mock fails as the interface is private and the import comes from another package.
As I'm not using the private interface, this would be a nice option to have to avoid the problem. The root cause could be fixed though, but maybe in another issue ? tell me @LandonTClipp :)

**Comment by LandonTClipp** [comment]
@matcornic Adding this feature would be pretty trivial. The provided example in the OP with `-exported=true` would work well enough, PRs are welcome, I'm not sure if I will have time to get to this this month, but we'll see.
