### ISSUE TITLE
Use Mockery to generate mock in directory

### ISSUE THREAD

**Issue by jasmineustc** [vektra/mockery#202]
Hi team, 

I have a question about generating mocks in package.  Here is the package directory. 

dir1 
    |_dir1sub1
                       |______dir1sub1_sub1
                                                |_____________File1.go
    |_dir1sub2
                      |_______File2.go

I defined interface for mockery in both File1.go and File2.go. I know that using "mockery -all -inpkg" could generate mocks inside the package, and using "mockery -all -output=aaa" could generate mocks inside one package with name "aaa". I'm wondering that can I generate the mocks inside the package and generate another directory like below?  Any kind of help is appreciated. 

dir1 
    |_dir1sub1
                       |_________dir1sub1_sub1
                                                |_________________File1.go
                                                |_________________mock
                                                                          |________________________File1_mock.go
    |_dir1sub2
                      |_________________File2.go
                      |_________________mock
                                                |________________________File1_mock.go

**Comment by lucianomda** [comment]
I am looking for exactly the same functionality

**Comment by LandonTClipp** [comment]
I'm open to the idea. If you want to submit a PR for this please feel free.

**Comment by ugurcanerdogan** [comment]
I am looking for the same functionality.

```
dir: "{{.InterfaceDir}}"
inpackage:true
```

parameters are not working!

**Comment by ugurcanerdogan** [comment]
You should not close all the issue unless they are resolved. You can label this issue as _help-wanted_, _feature-request_, or _open-to-pr_ but not close. If you continue with this practice like above, we will also need to search in the closed issues tab for the problems we experience. Someone who does not do this may not see the problem they are experiencing in the open-issues tab and may think that the problem has not been noticed at all, which significantly reduces the visibility of the problem in that version.


While I mentioned another problem in your approach to issues, the problem I experienced with the issue is still valid. Although I gave the **disable-func-mocks** parameter in mockery.yaml, mocks are still being generated for my definition of the type func. I could not see any explanation about disable-func-mocks parameter in the layouts section. I can also share a video upon request, but I do not think it will be more explanatory than what I have conveyed in writing this comment.  

![Image](https://github.com/user-attachments/assets/34f31956-e60c-4487-b22b-d1f5bbb43786)

![Image](https://github.com/user-attachments/assets/2bf3f11a-4899-4400-b173-16586ac06098)

![Image](https://github.com/user-attachments/assets/09298c67-472c-423f-8a5c-2420f21668cd)

**Comment by ugurcanerdogan** [comment]
You should not close all the issue unless they are resolved. You can label this issue as help-wanted, feature-request, or open-to-pr but not close. If you continue with this practice like above, we will also need to search in the closed issues tab for the problems we experience. Someone who does not do this may not see the problem they are experiencing in the open-issues tab and may think that the problem has not been noticed at all, which significantly reduces the visibility of the problem in that version.

While I mentioned another problem in your approach to issues, the problem I experienced with the issue and a new issue about disable-func-mocks is still valid. Although I gave the disable-func-mocks parameter in mockery.yaml, mocks are still being generated for my definition of the type func. I could not see any explanation about disable-func-mocks parameter in the layouts section. I can also share a video upon request, but I do not think it will be more explanatory than what I have conveyed in writing this comment. I would like to state that I expect your broad support in overcoming these problems.

Issue 1:

https://github.com/vektra/mockery/issues/716#issuecomment-2594908673

![Image](https://github.com/user-attachments/assets/2c241752-91f0-4057-8e6c-8b297f7b9ed0)

Issue 2:

![Image](https://github.com/user-attachments/assets/922033b8-062a-46b1-8cf7-cfa5e3dc0951)

![Image](https://github.com/user-attachments/assets/ae90645a-7590-4afe-884b-285055072fab)

![Image](https://github.com/user-attachments/assets/ce42139d-4170-4c46-87ef-8f0769644a39)
