### ISSUE TITLE
Idea: NOOP Generator

### ISSUE THREAD

**Issue by corsc** [vektra/mockery#207]
I really enjoy using Mockery; In particular, I love how I can keep my mocks "up to date" with `go generate` like this:
`//go:generate mockery -name=RateLimiter -case underscore -testonly -inpkg -note @generated`

I was wondering if you would accept an extension to mockery that generated NOOPs instead of mocks?
If you think this is "out of scope" that is fine, perhaps expected.  But with your permission, I would very much base any NOOP generator off the Mockery UX.

Thanks

**Comment by evanphx** [comment]
Not sure what you mean by NOOP in this context.

**Comment by corsc** [comment]
Sorry.  Stubs would be a different term.

**Comment by LandonTClipp** [comment]
I guess I'm open to the idea, but a no-op can already be "programmed" into testify's expectations. Obviously I'm in no place to tell you how to write your code, but wouldn't it be more explicit and clear to readers of your test if you write `mockObj.On("fun").Return(nil)` instead of implicitly baking this into your mocked object?

**Comment by corsc** [comment]
Thanks, @LandonTClipp. I was not aware of the `Maybe()` feature.

Generally, when I use NOOP stubs, I am looking for less explicit tests; for example, stubbing out instrumentation that is not being tested.

I guess I could do this with expectations+maybe and a function (to reduce the duplication).

Either way, thanks for considering it
