### ISSUE TITLE
Mock External Dependency

### ISSUE THREAD

**Issue by jon-whit** [vektra/mockery#227]
I'd like to use mockery to mock the behavior of the [`Conn`](https://godoc.org/github.com/gomodule/redigo/redis#Conn) interface defined in the [github.com/gomodule/redigo/redis](https://godoc.org/github.com/gomodule/redigo/redis) package. I'm quite new to the mockery package and am having difficulty understanding what I need to do to mock this external dependency. Here's a snippet of the Go code I'm dealing with:

```
type DataAccessLayer struct {
	RedisPool *redis.Pool
}

func (dal *DataAccessLayer) ListPosts() ([]*Post, error) {
    conn := dal.RedisPool.Get()
    defer conn.Close()

    resp, err := conn.Do("GET", "foo") // Want to mock this
    if err != nil {
        return nil, err
    }

    return deserialize(resp), nil
}
```

The [`redis.Pool`](
https://godoc.org/github.com/gomodule/redigo/redis#Pool) type implements the `Conn` interface, but the interface isn't embedded in the `DataAccessLayer` structure directly.

I'd like to be able to mock the `Do(commandName string, args ...interface{}) (reply interface{}, err error)` method of the `Conn` interface.

Something like:
```
mockObj.
    On("Do", "GET", []interface{}{"foo"}).
    Return(nil, errors.New("Redis error"))
```

Could someone point me in the right direction and give me some guidance? Any help would be much appreciated!

**Comment by HaywardMorihara** [comment]
_Disclaimer: I am by no means a expert and relatively new to this library and Go, so there may be a better solution than what I'm outlining here!_

The difficulty with what you have now is that you somehow need to get your mocked implementation of `redis.Conn`, but since you're directly calling `redis.Poll.Get()`, you won't be able to get your mocked implementation of `redis.Conn`.

A valid solution might be to have an interface for getting a connection, and then have a legitimate implementation for you production code, and a mock implementation for you test code. So you'd have some interface that gets a connection:
```
type ConnGetter interface{
	GetConn() redis.Conn
}
```
and then a legitimate production implementation:
```
type ConnGetterImpl struct {
	RedisPool *redis.Pool
}

func (cgi *ConnGetterImpl) GetConn() redis.Conn {
	return cgi.RedisPool.Get()
}
```
and then a mock implementation (that you'll be able to tell to return your mocked redis.Conn):
```
type ConnGetterMock struct {
	mock.Mock
	ConnGetter
}

func (cgm *ConnGetterMock) GetConn() redis.Conn {
	results := cgm.Called()
	conn, ok := results.Get(0).(redis.Conn)
	if !ok {
		conn = nil
	}
	return conn
}
```

Once you've defined your `ConnectionGetter`, you'll want your `DataAccessLayer` to get the connection through this new `ConnGetter` rather than directly from `redis.Pool`:
```
type DataAccessLayer struct {
	connGetter ConnGetter
}

func (dal *DataAccessLayer) ListPosts() ([]*Post, error) {
	conn := dal.connGetter.GetConn()
	defer conn.Close()

	resp, err := conn.Do("GET", "foo") // Want to mock this
	if err != nil {
		return nil, err
	}

	return deserialize(resp), nil
}
```

Now you can write your mock implementation of redis.Conn:
```
type ConnMock struct {
	mock.Mock
	redis.Conn
}

func (cm *ConnMock) Do(commandName string, args ...interface{}) (interface{}, error) {
	results := cm.Called(commandName, args)
	reply, ok := results.Get(0).(interface{})
	if !ok {
		reply = nil
	}
	err := results.Error(1)
	return reply, err
}

func (s *ConnMock) Close() error {
	return nil
}
```

and you should finally be able to write your test!
```
func TestListPosts(t *testing.T) {
	// Arrange
	mockObj := &ConnMock{}
	mockGetter := &ConnGetterMock{}
	dal := DataAccessLayer{connGetter: mockGetter}

	mockGetter.
		On("GetConn").
		Return(mockObj)

	mockObj.
		On("Do", "GET", []interface{}{"foo"}).
		Return(nil, errors.New("Redis error"))

	// Act
	response, err := dal.ListPosts()

	// Assert
	assert.Nil(t, response)
	assert.Equal(t, errors.New("Redis error"), err)
}
```

Hope this helps!

**Comment by jon-whit** [comment]
@HaywardMorihara yep, that's exactly what I did! Worked like a charm. Super slick!
