### ISSUE TITLE
Stop printing mockery version inside generated files

### ISSUE THREAD

**Issue by HarlamovBuldog** [vektra/mockery#298]
It was always 

> // Code generated by mockery v1.0.0. DO NOT EDIT.

But now everytime version changes it results in a lot of changes after you regenerate them. It's not such a big deal, just harder to review PRs, especially in big projects where there are a lot of mocks.
Btw this version mention here does not make a lof sense. // Code generated by mockery will be pretty enough.

**Comment by LandonTClipp** [comment]
Unfortunately since we're already under semantic versioning, doing this would break the major version so this is probably not something that can be done.

**Comment by HarlamovBuldog** [comment]
but it's just text inside generated file. Can it break smth at all? Somebody parse those headers inside files?

**Comment by LandonTClipp** [comment]
Well it wouldn't be appropriate to unexpectedly change everyone's mock files. I know it's kind of hypocritical of me to say that since we change mock files during bug fixes, but I think it's entirely possible somebody relies on having version information inside the mock. Plus, it also greatly aids in debugging mockery itself to have the version in there.

If there is sufficient demand in the community to remove it I will consider it more seriously but right now I think we lose more than we gain by not having it.

**Comment by HarlamovBuldog** [comment]
ok, I understand possible consequences, thanks for the fast response!
