### ISSUE TITLE
Working with private types

### ISSUE THREAD

**Issue by georgysavva** [vektra/mockery#320]
Hi. I have a private type that I want to mock. Since it's private mockery will generate a mock for it that will also be unexpected.
What if we add a flag that will force mockery to generate an exported mock type e.g. `--exported`.
I see at least two cases where it might help: 
1. Right now, the only way to put a private mock is inside the package dir i.e. to use `--inpackage ` flag. But what if I want to have a dedicated directory for my private mocks too, for example `internal/mocks`, the command would look like that: `mockery --name mytype --exported --output internal/mocks`
2. Assume I am using the `--inpackge` flag and my mock is inside the package dir. I want to access it in tests that are in the same dir, but in a separate package (with `_test` suffix), since mock type is also unexported I won't be able to use it my tests. This new flag could help to export the mock type just for tests: `mockery --name mytype --exported --inpackage --testonly`

I know that I can achieve the same result with the `--structname`, but I don't actually want to change the name, I just want to make it exported and using this flag would mean repeating your self in a way. 

If you like the idea I could shoot a PR with this.

**Comment by LandonTClipp** [comment]
The problem I am running into with this project is that the scope of the CLI flags has been creeping towards unnecessary complexity. I think the better way to handle cases like this is to use a `go generate` formula, where you give `//go:generate mockery --name unexportedName --structname ExportedName` or something like that. In fact, I think the ideal solution in an ideal world (possibly for v3) is to allow struct-specific overrides to mockery using the fully qualified name in a config file. So for instance if I wanted to override the name of [`github.com/vektra/mockery/pkg/fixtures/Requester`](https://github.com/vektra/mockery/blob/609f6ff95291a1b32772c669919ab366007a3240/pkg/fixtures/requester.go#L3) I could specify a config like this:

```yaml
github.com/vektra/mockery/pkg/fixtures:
  Requester:
    structName: NewRequester
```

This way the config listed here would override the "global" config provided in the `mockery` invocation. However, the current state of the code would probably make implementing this difficult/messy. The proper solution IMO was suggested by @nmiyake in https://github.com/vektra/mockery/issues/243#issuecomment-654488952 where mockery should iterate on module packages instead of walking subdirs.

Another issue with what you are proposing is the following: what if you have two structs `coolBar` and `CoolBar` in the same package? How would mockery handle that? Granted that would be bad practice but it's something you have to account for.

So in general, I want to start saying no to these kinds of features for v2, because they could be more cleanly and elegantly handled in the v3 model, and I want to avoid this feature creep.

**Comment by georgysavva** [comment]
> Another issue with what you are proposing is the following: what if you have two structs coolBar and CoolBar in the same package? How would mockery handle that? Granted that would be bad practice but it's something you have to account for.

But the situation is the same even if I use `--structname CoolBar`, right?

**Comment by LandonTClipp** [comment]
> > Another issue with what you are proposing is the following: what if you have two structs coolBar and CoolBar in the same package? How would mockery handle that? Granted that would be bad practice but it's something you have to account for.
> 
> But the situation is the same even if I use `--structname CoolBar`, right?

Ah yes. Well, when you are specifying it explicitly through `--structname` it is easier to tell mockery how to handle that situation, whereas telling it `--exported` posses an issue because you would have to tell it how to handle situations like this. It's just simply something we would have to define.

**Comment by georgysavva** [comment]
Thank you for explaining that. Lets wait for v3 then!
