### ISSUE TITLE
Mockery v2 build tags with vendors

### ISSUE THREAD

**Issue by A-Hilaly** [vektra/mockery#335]
Hi,

We are using `mockery` to generate mocks for multiple packages in [aws-controllers-k8s/Makefile](https://github.com/aws/aws-controllers-k8s/blob/main/Makefile#L61-L62).  One of the dependencies we have needs a specific build tag `codegen` [aws-sdk-go/private/model/api](https://github.com/aws/aws-sdk-go/blob/master/private/model/api/api.go#L1) . 
Mockery `v1.x.x` looks to be perfectly working with the `-tag=codegen` however with using mockery `v2.x.x` with the flag `--tags=codegen` doesn't seem to be working the same way.

Logs trying to generate mocks for `pkg/generate/config`:
```
mockery --tags="codegen" --case=underscore --output=mocks/pkg/generate --dir=./pkg/generate/config --all
24 Sep 20 12:04 CEST INF Starting mockery dry-run=false version=2.2.1
24 Sep 20 12:04 CEST INF Walking dry-run=false version=2.2.1
24 Sep 20 12:04 CEST ERR Error parsing file error="/Users/ahilaly/source/github.com/aws/aws-controllers-k8s/pkg/generate/config/config.go:210:60: Operation not declared by package api" dry-run=false version=2.2.1
```
I couldn't find an issue similar to this one. Is there any solution or work around for this issue? 

Thank you in advance!

Related issues: aws/aws-controllers-k8s#265

**Comment by LandonTClipp** [comment]
I actually think this may be happening because there is a mismatch in the mapstructure config name and the struct field name.

https://github.com/vektra/mockery/blob/master/pkg/config/config.go

mapstructure is expecting to find a `buildtags` name, but the CLI argument is providing `tags` instead. I think the fix is to just tell mapstructure to search for `tags`.

If you have the spare time, could you test this theory out, and if it works shoot a PR?

**Comment by A-Hilaly** [comment]
Thank you @LandonTClipp ! This worked for me. Sending a PR soon
