### ISSUE TITLE
Is it possible to use the module version with the --srcpkg param?

### ISSUE THREAD

**Issue by pushkargr** [vektra/mockery#347]
Hi,
I'm trying to use the --srcpkg param to generate mock for an external module and getting the error like below,

`➜ mockery --srcpkg github.com/hashicorp/go-hclog@1.14.1 --name=Format  

19 Nov 20 09:50 PST INF Starting mockery dry-run=false version=2.1.0

19 Nov 20 09:50 PST FTL Failed to load package github.com/hashicorp/go-hclog@1.14.1 error="-: can only use path@version syntax with 'go get'" dry-run=false version=2.1.0
`
Is there a way to achieve this?

Thanks

**Comment by LandonTClipp** [comment]
Hi @pushkargr. I looked into it a little bit and realized that `packages.Load` is making a call that looks like this:

```
[ltclipp@landon-virtualbox mockery]$ go list -e -json -compiled=false -test=false -export=false -deps=false -find=true -- github.com/hashicorp/go-hclog@v0.14.1
{
	"ImportPath": "github.com/hashicorp/go-hclog@v0.14.1",
	"Match": [
		"github.com/hashicorp/go-hclog@v0.14.1"
	],
	"Error": {
		"ImportStack": [
			"github.com/hashicorp/go-hclog@v0.14.1"
		],
		"Pos": "",
		"Err": "can only use path@version syntax with 'go get'"
	}
}
```

The issue is right in the error message actually, you can only use the `path@version` syntax when you `go get` something. So if you have already done `go get` on a specific version of the external package, it will already be in your go.mod file (if you're in module mode, which you should :wink:).

Example

```
[ltclipp@landon-virtualbox mockery]$ go get github.com/hashicorp/go-hclog@v0.15.0
[ltclipp@landon-virtualbox mockery]$ go list -e -json -compiled=false -test=false -export=false -deps=false -find=true -- github.com/hashicorp/go-hclog | grep Version
		"Version": "v0.15.0",
		"GoVersion": "1.13"
[ltclipp@landon-virtualbox mockery]$ go get github.com/hashicorp/go-hclog@v0.14.1
[ltclipp@landon-virtualbox mockery]$ go list -e -json -compiled=false -test=false -export=false -deps=false -find=true -- github.com/hashicorp/go-hclog | grep Version
		"Version": "v0.14.1",
		"GoVersion": "1.13"
```

So just get rid of the version string right?

```
[ltclipp@landon-virtualbox mockery]$ mockery --config /hello --srcpkg github.com/hashicorp/go-hclog --name=Format 
22 Nov 20 23:23 CST INF Starting mockery dry-run=false version=0.0.0-dev
22 Nov 20 23:23 CST INF Walking dry-run=false version=0.0.0-dev
22 Nov 20 23:23 CST FTL Unable to find 'Format' in any go files under this path dry-run=false version=0.0.0-dev
```

Bleh, this is a long-standing issue that I haven't had time to correct. So the hack I recommend people do is to have something like this in your source code.

```go
import "github.com/hashicorp/go-hclog"

type hclogFormat interface {
  hclog.Format
}
```

Then when you run mockery it will create a mock object that satisfies `hclog.Format`. But I don't even know if that's possible, because [`hclog.Format` is not an interface](https://pkg.go.dev/github.com/hashicorp/go-hclog#Format), so how will you make a mock for it?

**Comment by pushkargr** [comment]
Hey, @LandonTClipp Thanks for the reply. That makes sense and doing go get before mock works as well. Regarding the go-hclog I guess I gave a wrong example cause something like below works fine,

`mockery --srcpkg github.com/go-ldap/ldap/v3 --name=Client`
