### ISSUE TITLE
Feature request: Include command used to generate the mock in the mock

### ISSUE THREAD

**Issue by droberts-sea** [vektra/mockery#354]
An experience I've had several times:
1. Working on some code originally written by another engineer
2. Change an interface
3. Need to regenerate mocks for that interface
4. Spend 45 minutes figuring out how command line options fit together

It would be delightful if the mock file included a line at the top:

```go
// Code generated by mockery v2.3.0. DO NOT EDIT.
// This file was generated using the following command:
//   mockery --name Gizmo --dir pkg/widgets/gizmo --output pkg/widgets/mocks --filename gizmo.go --structname Gizmo
```

**Comment by LandonTClipp** [comment]
Hey there. The solution I recommend you use is use the .mockery.yaml file. This way the behavior will be cemented in your git repo (and version controlled).

**Comment by monfresh** [comment]
Can you please document what needs to go in the `.mockery.yaml` file? I couldn't find any examples. I've been trying to set `disable-version-string` but it's still adding the version number when it generates the mocks. Here's what my `.mockery.yaml` file looks like:
```
disable-version-string: true
structname: config_from_file
```
When I check `mockery showconfig`, it shows this:
```
Using config file: /Users/monfresh/projects/myproject/.mockery.yaml
all: false
buildtags: ""
case: camel
config: ""
cpuprofile: ""
dir: .
disableversionstring: true
dryrun: false
exported: false
filename: ""
inpackage: false
keeptree: false
loglevel: info
name: ""
note: ""
outpkg: mocks
packageprefix: ""
output: ./mocks
print: false
profile: ""
quiet: false
recursive: false
srcpkg: ""
boilerplatefile: ""
structname: config_from_file
tags: ""
testonly: false
unrollvariadic: true
version: false
```

**Comment by monfresh** [comment]
I think it might be because we are using `go generate`. Is there a recommended way to specify the `disable-version-string` flag via an ENV var? I tried all of these variations. but none worked:

`MOCKERY_DISABLE_VERSION_STRING=true`
`DISABLE_VERSION_STRING=true`
`DISABLEVERSIONSTRING=true` 
`MOCKERY_DISABLEVERSIONSTRING=true`

**Comment by LandonTClipp** [comment]
Upon further thought, I realized that mockery probably needs to be modified so that it will search for `.mockery.yaml` on every path up to root of the CWD. go generate's CWD will be at the file with the `generate` invocation. It won't find .mockery.yaml here, so obviously any config you provide will fail. If it searches upwards for `.mockery.yaml` it will eventually find your project's config.

**Comment by monfresh** [comment]
That sounds right. Thanks for thinking this through with me!

**Comment by samuel-sts** [comment]
> I think it might be because we are using `go generate`. Is there a recommended way to specify the `disable-version-string` flag via an ENV var? I tried all of these variations, but none worked:
> 
> `MOCKERY_DISABLE_VERSION_STRING=true`
> `DISABLE_VERSION_STRING=true`
> `DISABLEVERSIONSTRING=true`
> `MOCKERY_DISABLEVERSIONSTRING=true`

I had the same issue. Maybe it doesn't a good solution because you need to repeat an arg `--disable-version-string` on which command, but I used a workaround.

`//go:generate mockery --name=Reader|Writer --disable-version-string`

**Comment by LandonTClipp** [comment]
Closing this as mockery searches upwards from the cwd for .mockery.yaml.
