### ISSUE TITLE
Run with docker extremely slow

### ISSUE THREAD

**Issue by dustin-graham** [vektra/mockery#369]
Hello. Thank you for this great tool! I previously used this tool via Homebrew installation. However, since I upgraded to Go 1.16 it became incompatible with my dev setup. As a result, I chose to start using it via Docker. However, I found that executing this tool via docker is extremely slow. It takes about 3 minutes to generate the interface I provide via --name --recursive. I'm not sure how to remedy this. If you have any hints as to why it may be executing so slowly, please let me know.

**Comment by LandonTClipp** [comment]
Some other folks recently submitted a PR to build mockery with go 1.16. Hopefully this will fix your problem, let me know if you continue to have issues.

**Comment by simplylizz** [comment]
It seems that the problem is still here.

v2.7.4:
* locally installed - 2 minutes;
* installed in Docker - 7 minutes (ran it twice in the same container to ensure that it's not a matter of cache or something like this, result was the same);

**Comment by SVilgelm** [comment]
@dustin-graham @simplylizz I'm facing same issue with other tools, like `golangci-lint` and etc..., especially in case there are many other containers are running at same time. You can try to stop other container and run only `mockery`, try to give more resource in the docker settings. 
I really tried different ways and didn't;t found a good solution.


@dustin-graham Could you please five a bit more details about this: 
> However, since I upgraded to Go 1.16 it became incompatible with my dev setup.

I'm using mockery with go1.16 and no problems, except on Mac with M1 chip, but it's not because of go's versions.

**Comment by DeadlySurgeon** [comment]
This is still an issue, and on the M1 chips it reaches an OOM and potentially crashes Docker.
