### ISSUE TITLE
The version in generated file headers has two v's

### ISSUE THREAD

**Issue by lionello** [vektra/mockery#372]
Files generated with version v2.7.1 have the following header:
```
// Code generated by mockery vv2.7.1. DO NOT EDIT.
```

Notice the two v's.

**Comment by LandonTClipp** [comment]
Woops, I will fix. Thaks.

**Comment by monfresh** [comment]
@lionello I'm curious how you got `vv2.7.1` to show up in your generated files. How did you install mockery and how did you run it? I'm asking because I'm seeing `0.0.0-dev` in my generated files, as reported in this issue: https://github.com/vektra/mockery/issues/381. Our `go.sum` shows that we are using version 2.7.5.

**Comment by lionello** [comment]
If I recall correctly, I think that happened with one particular version. The latest shows `v0.0.0-dev`.
