### ISSUE TITLE
Trying to use "go get" in github action.

### ISSUE THREAD

**Issue by ygworldr** [vektra/mockery#385]
I am doing this in my GitHub action:

```yaml
      - name: "Install dependencies"
        run: GO111MODULE=off go get -v github.com/vektra/mockery/v2/.../
```

When it runs, I am getting this error:

```bash
GO111MODULE=off go get -v github.com/vektra/mockery/v2/.../
github.com/vektra/mockery (download)
go: warning: "github.com/vektra/mockery/v2/..." matched no packages
```

Obviously, mockery is not installed and thus I cannot generate mocks.

Am I doing something wrong?

**Comment by MrDOS** [comment]
Setting `GO111MODULE=off` to force a global install also disables Go modules, so you can't refer to a module version (in this case, `v2`). You have two options:

* If you're on Go 1.16+, you can use the new [`go install` command](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies). This is preferable if you have a recent Go toolchain available.
* Otherwise, you can run the `go get` without forcing `GO111MODULE` to `off` from outside of a Go module directory. For example, `pushd /tmp && go get -v github.com/vektra/mockery/v2/.../ && popd`.

**Comment by LandonTClipp** [comment]
Closing this ticket for inactivity. Please comment on this to have it re-opened, or create a new ticket if this is still a problem. Thanks!
