### ISSUE TITLE
Wrong code for methods with varargs

### ISSUE THREAD

**Issue by fabiokung** [vektra/mockery#44]
Code generated for Mocks of methods with varargs won't compile. Example:

```go
func (m *Interface) SomeMethod(_a0 Type1, _a1 ...Type2) error {
	ret := m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Type1, ...Type2) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

But it should be:

```go
func (m *Interface) SomeMethod(_a0 Type1, _a1 ...Type2) error {
	ret := m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Type1, ...Type2) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

**Comment by ryanbrainard** [comment]
Looks like this was already fixed in https://github.com/vektra/mockery/commit/5a49587472c272e8fcd772c4dfa7f64388c795af. 

I fixed it separately in my fork in https://github.com/ryanbrainard/mockery/pull/3 and https://github.com/ryanbrainard/mockery/pull/4. Was going to send a patch upstream, but looks like I don't need to and this can be closed.
