### ISSUE TITLE
Feature Request: ProxyMock

### ISSUE THREAD

**Issue by distinctdan** [vektra/mockery#446]
Description
-------------
It can sometimes be useful to mock or spy on a single method in an interface. For example, I've got a large database interface, and I want it to respond normally except for 1 method. I could manually build a mock for it, but it would be a lot of work to add passthrough implementations for all the methods I don't care about. So, I was thinking that it could be possible to generate a mock that calls the original object if a method hasn't been mocked. I'm calling this a "ProxyMock".

Example for mocking a single method:
```
package main

type DBInterface interface {
	CreateItem(item Item) (id int, err error)
	ReadItem(id int)      (item Item, err error)
}

type DB struct {}
// Implementations for CreateItem and ReadItem

TestReadItemError(t *testing.T) {
	realDB := DB{}
        // Pass a real object to the mock so that it can call its methods.
	mock := proxymocks.NewDB(&readDB)

	// Make "ReadItem" return an error. All other db methods will respond normally.
	mock.On("ReadItem", 1).
		Return(someError)

	// Does the real call
	mock.CreateItem(someItem)

	// Returns the mocked error
	readItem, err := mock.ReadItem(1)
}
```

This technique could also be used to spy on methods without affecting the behavior. Any thoughts? Would love to hear if this could be viable.

**Comment by LandonTClipp** [comment]
Hi there. I think from a technical standpoint this is pretty easy to implement and sounds like a cool idea. The motivation for it however might be an anti pattern. For unit tests, testing against a real database is usually discouraged. For integration tests against a database, you'd typically just query the database after committing, instead of inspecting the call.

The other potential issue with this as it stands is that there's not really a sensible way (besides maybe go generate, which I personally don't use a lot) to differentiate how mocks are generated for specific interfaces. It's an improvement I'm thinking of doing in v3. But you'd need some kind of config that defines that a ProxyMock should be made for a specific interface, but not others.

Something to think about. I'm not against it in principle, but I think we'd need to sort through the motivation a bit more.

**Comment by distinctdan** [comment]
Gotcha, thanks for the info. To tell you a bit more about my use case, we've got a bunch of integration tests, and 99% of them are able to run in parallel. However, we've got one test that tests "running active jobs" end to end. So it scans the db for all active jobs and runs them. The problem is that if other tests create jobs (which they do), they get picked up by this test, and it throws off the expected results. My idea is to use a ProxyMock to intercept the db call to get the jobs, and filter it to only include the job that this test created.

Looking at this more, my use case may be a bit niche. It is useful if you want to spy on or modify individual function calls, but I think you're right that generally it's better to assert on results rather than inspecting calls.
