### ISSUE TITLE
Operate on packages/modules instead of directories.

### ISSUE THREAD

**Issue by LandonTClipp** [vektra/mockery#526]
https://github.com/vektra/mockery/issues/243#issuecomment-654488952

**Comment by mattdowdell** [comment]
+1 for this feature. My team recently stumbled onto the limitations of operating on directories when working on a module with another modules in a subdirectory, e.g. `/path/to/module1 and `/path/to/module1/module2`. We generated mocks such that they end up in `/path/to/module1/mocks/` which ended up causing a circulr dependency because:

- Module2 import Module1.
- Module1's mocks are part of the Module1 module.
- Module1's mocks import Module2.

Our workaround was to generate the Module1 mocks and then delete those that were for Module2 before any other tooling could choke on them, e.g. testing, linting, etc.
