### ISSUE TITLE
Avoid trying to mock the generated mocks

### ISSUE THREAD

**Issue by guettli** [vektra/mockery#721]
Description
-------------

I used `recursive: True`, and then mockery tries to mock the generated mocks.

Since I added a new method to the interface, mockery fails.

```
❯ make generate-mocks 
mockery --version
10 Oct 23 10:57 CEST INF couldn't read any config file version=v2.35.3
10 Oct 23 10:57 CEST INF Starting mockery dry-run=false version=v2.35.3
10 Oct 23 10:57 CEST INF Using config:  dry-run=false version=v2.35.3
v2.35.3
cd pkg/services/baremetal/client; go run github.com/vektra/mockery/v2@v2.35.3
10 Oct 23 10:57 CEST INF Starting mockery dry-run=false version=v2.35.3
10 Oct 23 10:57 CEST INF Using config: /home/guettli/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/.mockery.yaml dry-run=false version=v2.35.3
10 Oct 23 10:57 CEST ERR encountered error when loading package error="-: # github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks\nmocks/factory.go:55:10: cannot use f.rescueClient (variable of type *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client) as sshclient.Client value in return statement: *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client does not implement sshclient.Client (missing method GetCloudInitOutput)\nmocks/factory.go:58:10: cannot use f.osClientAfterCloudInit (variable of type *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client) as sshclient.Client value in return statement: *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client does not implement sshclient.Client (missing method GetCloudInitOutput)\nmocks/factory.go:60:9: cannot use f.osClientAfterInstallImage (variable of type *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client) as sshclient.Client value in return statement: *\"github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/mocks/ssh\".Client does not implement sshclient.Client (missing method GetCloudInitOutput)" dry-run=false version=v2.35.3
```

Mockery Version
--------

v2.35.3

Golang Version
--------------

go version go1.21.0 linux/amd64

Installation Method
-------------------

- [ ] Binary Distribution
- [ ] Docker
- [ ] brew
- [ ] go install
- [x] Other: `go run github.com/vektra/mockery/v2@v2.35.3`

Steps to Reproduce
------------------

1. Create mocks in directory "mock"
1. Extend the interface
1. use `recursive: True`
1. See error like above

### Expected Behavior

Mockery should not mock read the code which it has generated.

**Comment by LandonTClipp** [comment]
So, I haven't dug into this so I might be wrong, but I think what's happening here is _not_ that mockery is trying to generate mocks, but rather that it simply parses the mock package you have to see if there are any interfaces we can generate mocks for. If mockery can't parse it then I'd bet there's something syntactically wrong with the generated mock file anyway.

You could try setting `include-auto-generated: false` in your config. This causes mockery to search the first few lines of every `.go` file for the `DO NOT EDIT` string and exclude the file if so. This bypasses the Go parser so you won't run into the issue.

The other thing you could try is using `exclude: ["mocks"]` so that mockery will not traverse down that path at all, no matter what.

**Comment by guettli** [comment]
@LandonTClipp thank you for your answer. I use `all: True` now, and it works as expected.
